export const symptoms = [
  { label: "Itching", value: "itching" },
  { label: "Skin Rash", value: "skin_rash" },
  { label: "Nodal Skin Eruption", value: "nodal_skin_eruptions" },
  { label: "Continuous Sneezing", value: "continuous_sneezing" },
  { label: "Shivering", value: "shivering" },
  { label: "Chills", value: "chills" },
  { label: "Joint pain", value: "joint_pain" },
  { label: "Stomach Pain", value: "stomach_pain" },
  { label: "Acidity", value: "acidity" },
  { label: "Ulcers on tongue", value: "ulcers_on_tongue" },
  { label: "Muscle wasting", value: "muscle_wasting" },
  { label: "Vomiting", value: "vomiting" },
  { label: "Burning micturition", value: "burning_micturition" },
  { label: "Spotting urination", value: "spotting_urination" },
  { label: "Fatigue", value: "fatigue" },
  { label: "Weight gain", value: "weight_gain" },
  { label: "Anxiety", value: "anxiety" },
  { label: "Cold hands and feets", value: "cold_hand_and_feets" },
  { label: "Mood swings", value: "mood_swings" },
  { label: "Weight loss", value: "weight_loss" },
  { label: "Restlessness", value: "restlessness" },
  { label: "Lethargy", value: "lethargy" },
  { label: "Patches in throat", value: "patches_in_throat" },
  { label: "Irregular sugar level", value: "irregular_sugar_level" },
  { label: "Cough", value: "cough" },
  { label: "High fever", value: "high_fever" },
  { label: "Sunken eyes", value: "sunken_eyes" },
  { label: "Breathlessness", value: "breathlessness" },
  { label: "Sweating", value: "sweating" },
  { label: "Dehydration", value: "dehydration" },
  { label: "Indigestion", value: "indigestion" },
  { label: "Headache", value: "headache" },
  { label: "Yellowish skin", value: "yellowish_skin" },
  { label: "Dark urine", value: "dark_urine" },
  { label: "Nausea", value: "nausea" },
  { label: "Loss of appetite", value: "loss_of_appetite" },
  { label: "Pain behind eyes", value: "pain_behind_the_eyes" },
  { label: "Back pain", value: "back_pain" },
  { label: "Constipation", value: "constipation" },
  { label: "Abdominal Pain", value: "abdominal_pain" },
  { label: "Diarrhoea", value: "diarrhoea" },
  { label: "Mild Fever", value: "mild_fever" },
  { label: "Yellow urine", value: "yellow_urine" },
  { label: "Yellowing of eyes", value: "yellowing_of_eyes" },
  { label: "Acute liver failure", value: "acute_liver_failure" },
  { label: "Swelling of stomach", value: "swelling_of_stomach" },
  { label: "Swelled lymph nodes", value: "swelled_lymph_nodes" },
  { label: "Malaise", value: "malaise" },
  { label: "Blurred Vision", value: "blurred_and_distorted_vision" },
  { label: "Phlegm", value: "phlegm" },
  { label: "Throat irritation", value: "throat_irritation" },
  { label: "Redness of eyes", value: "redness_of_eyes" },
  { label: "Sinus pressure", value: "sinus_pressure" },
  { label: "Runny nose", value: "runny_nose" },
  { label: "Congestion", value: "congestion" },
  { label: "Chest Pain", value: "chest_pain" },
  { label: "Weakness in limbs", value: "weakness_in_limbs" },
  { label: "Fast heart rate", value: "fast_heart-rate" },
  {
    label: "Pain during bowel movements",
    value: "pain_during_bowel_movements",
  },
  { label: "Pain in anal", value: "pain_in_anal_region" },
  { label: "Blood stool", value: "blood_stool" },
  { label: "Irritation in anus", value: "irritation_in_anus" },
  { label: "Neck Pain", value: "neck_pain" },
  { label: "Dizziness", value: "dizziness" },
  { label: "Cramps", value: "cramps" },
  { label: "Bruising", value: "bruising" },
  { label: "Obesity", value: "obesity" },
  { label: "Swollen legs", value: "swollen_legs" },
  { label: "Swollen blood vessels", value: "swollen_blood_vessels" },
  { label: "Puffy face and eyes", value: "puffy_face_and_eyes" },
  { label: "Enlarged thyroid", value: "enlarged_thyroid" },
  { label: "Brittle nails", value: "brittle_nails" },
  { label: "Swollen extremeties", value: "swollen_extremeties" },
  { label: "Extra material contacts", value: "extra_material_contacts" },
  { label: "Excessive Hunger", value: "excessive_hunger" },
  { label: "Drying and tingling lips", value: "drying_and_tingling_lips" },
  { label: "Slurred speech", value: "slurred_speech" },
  { label: "Knee pain", value: "knee_pain" },
  { label: "Muscle weakness", value: "muslce_weakness" },
  { label: "Hip joint pain", value: "hip_joint_pain" },
  { label: "Stiff neck", value: "stiff_neck" },
  { label: "Swelling joints", value: "swelling_joints" },
  { label: "Movement stiffness", value: "movement_stiffness" },
  { label: "Spinning movements", value: "spinning_movements" },
  { label: "Loss of balance", value: "loss_of_balance" },
  { label: "Unsteadiness", value: "unsteadiness" },
  { label: "Weakness of one body side", value: "weakness_of_one_body_side" },
  { label: "Loss of smell", value: "loss_of_smell" },
  { label: "Bladder discomfort", value: "bladder_discomfort" },
  { label: "Foul smell of urine", value: "foul_smell_of_urine" },
  { label: "Continuous feel of urine", value: "continuous_feel_of_urine" },
  { label: "Passage of gases", value: "passage_of_gases" },
  { label: "Internal Itching", value: "internal_itching" },
  { label: "Toxic look(typhosis)", value: "toxic_look(typhosis)" },
  { label: "Depression", value: "depression" },
  { label: "Irritability", value: "irritability" },
  { label: "Muscle Pain", value: "muscle_pain" },
  { label: "Altered sensorium", value: "altered_sensorium" },
  { label: "Red spor over body", value: "red_spot_over_body" },
  { label: "Belly pain", value: "belly_pain" },
  { label: "Abnormal menstruation", value: "abnormal_menstruation" },
  { label: "Dischromic patches", value: "dischromic _patches" },
  { label: "Watering from eyes", value: "watering_from_eyes" },
  { label: "Increased appetite", value: "increased_appetite" },
  { label: "Polyuria", value: "polyuria" },
  { label: "Family history", value: "family_history" },
  { label: "Mucoid Sputum", value: "mucoid_sputum" },
  { label: "Rusty_sputum", value: "rusty_sputum" },
  { label: "Lack of concentration", value: "lack_of_concentration" },
  { label: "Visual disturbance", value: "visual disturbance" },
  {
    label: "Receiving blood transfusion",
    value: "receiving_blood_transfusion",
  },
  {
    label: "Receiving unsterile injection",
    value: "receiving_unsterile_injections",
  },
  { label: "Coma", value: "Coma" },
  { label: "Stomach bleeding", value: "stomach_bleeding" },
  { label: "Distention of abdomen", value: "distention_of_abdomen" },
  { label: "Alcohol consumption", value: "history_of_alcohol_consumption" },
  { label: "Fluid overload", value: "fluid_overload" },
  { label: "Blood in sputum", value: "blood_in_sputum" },
  { label: "Prominent veins on calf", value: "prominent_veins_on_calf" },
  { label: "Palpitation", value: "palpitation" },
  { label: "Painful walking", value: "painful_walking" },
  { label: "Pus filled pimples", value: "pus_filled_pimples" },
  { label: "Blackheads", value: "blackheads" },
  { label: "Scurring", value: "scurring" },
  { label: "Skin peeling", value: "skin_peeling" },
  { label: "Silver like dusting", value: "silver_like_dusting" },
  { label: "Small dents in nails", value: "small_dents_in_nails" },
  { label: "Inflammatory nails", value: "inflammatory_nails" },
  { label: "Blister", value: "blister" },
  { label: "Red sore around nose", value: "red_sore_around_nose" },
  { label: "Yellow Crust", value: "yellow_crust_ooze" },
];
